/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: deviceapps.proto */

#ifndef PROTOBUF_C_deviceapps_2eproto__INCLUDED
#define PROTOBUF_C_deviceapps_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _DeviceApps DeviceApps;
typedef struct _DeviceApps__Device DeviceApps__Device;


/* --- enums --- */


/* --- messages --- */

struct  _DeviceApps__Device
{
  ProtobufCMessage base;
  protobuf_c_boolean has_id;
  ProtobufCBinaryData id;
  protobuf_c_boolean has_type;
  ProtobufCBinaryData type;
};
#define DEVICE_APPS__DEVICE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&device_apps__device__descriptor) \
    , 0,{0,NULL}, 0,{0,NULL} }


struct  _DeviceApps
{
  ProtobufCMessage base;
  DeviceApps__Device *device;
  size_t n_apps;
  uint32_t *apps;
  protobuf_c_boolean has_lat;
  double lat;
  protobuf_c_boolean has_lon;
  double lon;
};
#define DEVICE_APPS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&device_apps__descriptor) \
    , NULL, 0,NULL, 0,0, 0,0 }


/* DeviceApps__Device methods */
void   device_apps__device__init
                     (DeviceApps__Device         *message);
/* DeviceApps methods */
void   device_apps__init
                     (DeviceApps         *message);
size_t device_apps__get_packed_size
                     (const DeviceApps   *message);
size_t device_apps__pack
                     (const DeviceApps   *message,
                      uint8_t             *out);
size_t device_apps__pack_to_buffer
                     (const DeviceApps   *message,
                      ProtobufCBuffer     *buffer);
DeviceApps *
       device_apps__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   device_apps__free_unpacked
                     (DeviceApps *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DeviceApps__Device_Closure)
                 (const DeviceApps__Device *message,
                  void *closure_data);
typedef void (*DeviceApps_Closure)
                 (const DeviceApps *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor device_apps__descriptor;
extern const ProtobufCMessageDescriptor device_apps__device__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_deviceapps_2eproto__INCLUDED */
