/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: deviceapps.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "deviceapps.pb-c.h"
void   device_apps__device__init
                     (DeviceApps__Device         *message)
{
  static DeviceApps__Device init_value = DEVICE_APPS__DEVICE__INIT;
  *message = init_value;
}
void   device_apps__init
                     (DeviceApps         *message)
{
  static DeviceApps init_value = DEVICE_APPS__INIT;
  *message = init_value;
}
size_t device_apps__get_packed_size
                     (const DeviceApps *message)
{
  assert(message->base.descriptor == &device_apps__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_apps__pack
                     (const DeviceApps *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_apps__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_apps__pack_to_buffer
                     (const DeviceApps *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_apps__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceApps *
       device_apps__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceApps *)
     protobuf_c_message_unpack (&device_apps__descriptor,
                                allocator, len, data);
}
void   device_apps__free_unpacked
                     (DeviceApps *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &device_apps__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor device_apps__device__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(DeviceApps__Device, has_id),
    offsetof(DeviceApps__Device, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(DeviceApps__Device, has_type),
    offsetof(DeviceApps__Device, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_apps__device__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange device_apps__device__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor device_apps__device__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceApps.Device",
  "Device",
  "DeviceApps__Device",
  "",
  sizeof(DeviceApps__Device),
  2,
  device_apps__device__field_descriptors,
  device_apps__device__field_indices_by_name,
  1,  device_apps__device__number_ranges,
  (ProtobufCMessageInit) device_apps__device__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_apps__field_descriptors[4] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DeviceApps, device),
    &device_apps__device__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "apps",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DeviceApps, n_apps),
    offsetof(DeviceApps, apps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(DeviceApps, has_lat),
    offsetof(DeviceApps, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lon",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(DeviceApps, has_lon),
    offsetof(DeviceApps, lon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_apps__field_indices_by_name[] = {
  1,   /* field[1] = apps */
  0,   /* field[0] = device */
  2,   /* field[2] = lat */
  3,   /* field[3] = lon */
};
static const ProtobufCIntRange device_apps__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor device_apps__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceApps",
  "DeviceApps",
  "DeviceApps",
  "",
  sizeof(DeviceApps),
  4,
  device_apps__field_descriptors,
  device_apps__field_indices_by_name,
  1,  device_apps__number_ranges,
  (ProtobufCMessageInit) device_apps__init,
  NULL,NULL,NULL    /* reserved[123] */
};
