# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0003_answervote_questionvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='answervote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answervote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questionvote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionvote',
            name='user',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='votes',
            new_name='total_votes',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='votes',
            new_name='total_votes',
        ),
        migrations.DeleteModel(
            name='AnswerVote',
        ),
        migrations.DeleteModel(
            name='QuestionVote',
        ),
    ]
